{{- if and .Values.rbacEnable .Values.rbacCreateClusterRole }}
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    app: {{ template "casskop.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "casskop.name" . }}
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "watch", "list"]
- apiGroups:
    - db.orange.com
  resources:
    - "cassandraclusters"
    - "cassandrabackups"
    - "cassandrarestores"
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
    - deletecollection
- apiGroups:
    - db.orange.com
  resources:
    - cassandraclusters/status
    - cassandrabackups/status
    - cassandrarestores/status
  verbs:
    - get
    - update
    - patch
- apiGroups:
    - ""
  resources:
    - pods
    - pods/exec
    - services
    - endpoints
    - persistentvolumeclaims
    - events
    - configmaps
    - secrets
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - ""
  resources:
    - namespaces
  verbs:
    - get
- apiGroups:
    - apps
  resources:
    - deployments
    - daemonsets
    - replicasets
    - statefulsets
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - policy
  resources:
    - poddisruptionbudgets
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - monitoring.coreos.com
  resources:
    - servicemonitors
  verbs:
    - "get"
    - "create"
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    app: {{ template "casskop.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "casskop.name" . }}-cluster-node
rules:
  - apiGroups: [""]
    resources: ["pods", "configmaps", "secrets" ]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["get","create"]
{{- end }}
